services:
  postgres:
    image: 'ghcr.io/postgresml/postgresml:2.7.13'
    command: sleep infinity
    ports:
      - '5432:5432'
    volumes:
      - 'postgresml_data:/var/lib/postgresql'

volumes:
  postgresml_data: {}